/********************************************************************************
** Form generated from reading UI file 'miniPS.ui'
**
** Created by: Qt User Interface Compiler version 5.9.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MINIPS_H
#define UI_MINIPS_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QScrollArea>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_miniPSClass
{
public:
    QAction *actionopen_image;
    QAction *actionsave_image;
    QAction *actionminimize;
    QAction *actionundo;
    QAction *actionfull_screen;
    QAction *actionwindowed;
    QAction *actionexit;
    QAction *actionclean_all_layers;
    QAction *actionRGB2GrayScale;
    QAction *actionRed;
    QAction *actionGreen;
    QAction *actionBlue;
    QAction *actionHSB;
    QAction *actionOtus_Algo;
    QAction *actiondouble_threshod;
    QAction *actionresize;
    QAction *actionR_hist;
    QAction *actionG_hist;
    QAction *actionB_hist;
    QAction *actionEqualization;
    QAction *actionrotate;
    QAction *actionlinear;
    QAction *actionexp_log;
    QAction *actionlogarithm;
    QAction *actionfilter_2;
    QAction *action3_3_self_define;
    QAction *actionlaplace;
    QAction *actioncanny;
    QAction *actionsobelX;
    QAction *actionsobelY;
    QAction *actionsobelXY;
    QAction *actiongrayscale_mophology;
    QAction *actionhoughLine;
    QAction *actionhoughCircle;
    QAction *actiondilation;
    QAction *actionerosion;
    QAction *actionopen;
    QAction *actionclose;
    QAction *actionthinning_binary;
    QAction *actionthickening_binary_only;
    QAction *actiondistance_transform_binary_only;
    QAction *actionskeleton_binary_only;
    QAction *actionskeleton_reconstruction_binary_only;
    QAction *actionwatershed;
    QAction *actionbinary;
    QAction *actiongrayscale;
    QAction *actionmophology;
    QAction *actionDocument;
    QWidget *centralWidget;
    QPushButton *exitBtn;
    QGroupBox *groupBox;
    QFrame *line;
    QFrame *line_2;
    QSlider *horizontalSlider;
    QPushButton *zoomOutBtn;
    QPushButton *zoomInBtn;
    QLabel *label_scaleVal;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_posX;
    QLabel *label_posY;
    QLabel *label_width;
    QLabel *label_height;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_rVal;
    QLabel *label_gVal;
    QLabel *label_bVal;
    QTabWidget *tabWidget;
    QWidget *layer1;
    QScrollArea *scrollArea;
    QWidget *scrollAreaWidgetContents;
    QWidget *layer2;
    QScrollArea *scrollArea_2;
    QWidget *scrollAreaWidgetContents_2;
    QWidget *layer3;
    QScrollArea *scrollArea_3;
    QWidget *scrollAreaWidgetContents_3;
    QWidget *layer4;
    QScrollArea *scrollArea_4;
    QWidget *scrollAreaWidgetContents_4;
    QWidget *layer5;
    QScrollArea *scrollArea_5;
    QWidget *scrollAreaWidgetContents_5;
    QLabel *label_imagesize;
    QWidget *leftToolBar;
    QPushButton *normalModeBtn;
    QPushButton *slctModeBtn;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QFrame *line_3;
    QLabel *picked_color1;
    QLabel *picked_color2;
    QPushButton *colorSwitchBtn;
    QPushButton *colorResetBtn;
    QPushButton *getColorBtn;
    QPushButton *cutBtn;
    QPushButton *addBtn;
    QPushButton *subtractionBtn;
    QPushButton *multiplicationBtn;
    QPushButton *spinBtn;
    QPushButton *helloWorldBtn;
    QFrame *line_4;
    QFrame *line_6;
    QFrame *line_7;
    QFrame *line_5;
    QWidget *containerWidget;
    QWidget *hsvWidget;
    QSlider *horizontalSlider_h;
    QSlider *horizontalSlider_s;
    QSlider *horizontalSlider_v;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QPushButton *HSVokBtn;
    QWidget *doubleThreshodWidget;
    QSpinBox *inputThreshod1;
    QLabel *label_12;
    QLabel *label_13;
    QSpinBox *inputThreshod2;
    QPushButton *doubleThreshodOkBtn;
    QWidget *addWidget;
    QLabel *label_8;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QSpinBox *inputAddImg1;
    QSpinBox *inputAddImg2;
    QPushButton *addOkBtn;
    QDoubleSpinBox *inputAddWeight1;
    QDoubleSpinBox *inputAddWeight2;
    QLabel *label_18;
    QLabel *label_19;
    QSpinBox *inputAddX;
    QSpinBox *inputAddY;
    QWidget *subtractionWidget;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QSpinBox *inputSubImg1;
    QSpinBox *inputSub2;
    QSpinBox *inputSubX;
    QSpinBox *inputSubY;
    QPushButton *substractionOkBtn;
    QWidget *multiplicationWidget;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QSpinBox *inputMultiImg1;
    QSpinBox *inputMultiImg2;
    QPushButton *multiplicationOkBtn;
    QWidget *divisionWidget;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QSpinBox *inputDvdImg1;
    QSpinBox *inputDvdImg2;
    QPushButton *divisionOkBtn;
    QWidget *resizeWidget;
    QLabel *label_31;
    QCheckBox *inputChoiceLINEAR;
    QCheckBox *inputChoiceNN;
    QLabel *label_32;
    QSpinBox *inputResizeWidth;
    QLabel *label_33;
    QSpinBox *inputResizeHeight;
    QPushButton *resizeOkBtn;
    QWidget *filterWidget;
    QLabel *label_34;
    QCheckBox *inputFilterChoiceBox;
    QCheckBox *inputFilterChoiceMedian;
    QCheckBox *inputFilterChoiceGaussian;
    QLabel *label_35;
    QSpinBox *inputKernelSize;
    QPushButton *filterOkBtn;
    QWidget *rotateWidget;
    QLabel *label_36;
    QDoubleSpinBox *inputRotateTheta;
    QLabel *label_37;
    QPushButton *rotateOkBtn;
    QCheckBox *inputRotateChoiceNN;
    QCheckBox *inputRotateChoiceLINEAR;
    QLabel *label_38;
    QWidget *GSAWidget;
    QLabel *label_39;
    QSlider *GSASliderD;
    QSlider *GSASliderC;
    QSlider *GSASliderA;
    QSlider *GSASliderB;
    QLabel *label_40;
    QPushButton *GSALinearOkBtn;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QLabel *label_44;
    QCheckBox *inputLinearGSAChoiceRGB;
    QCheckBox *inputLinearGSAChoiceR;
    QCheckBox *inputLinearGSAChoiceG;
    QCheckBox *inputLinearGSAChoiceB;
    QWidget *UGSAWidget;
    QLabel *label_45;
    QLabel *label_46;
    QLabel *label_47;
    QLabel *label_48;
    QDoubleSpinBox *inputUGSAA;
    QDoubleSpinBox *inputUGSAB;
    QDoubleSpinBox *inputUGSAC;
    QCheckBox *inputUGSAexp;
    QCheckBox *inputUGSAlog;
    QPushButton *UGSAOkBtn;
    QWidget *selfFilterWidget;
    QLabel *label_49;
    QDoubleSpinBox *inputSelfFilter1;
    QDoubleSpinBox *inputSelfFilter2;
    QDoubleSpinBox *inputSelfFilter3;
    QDoubleSpinBox *inputSelfFilter4;
    QDoubleSpinBox *inputSelfFilter5;
    QDoubleSpinBox *inputSelfFilter6;
    QDoubleSpinBox *inputSelfFilter7;
    QDoubleSpinBox *inputSelfFilter8;
    QDoubleSpinBox *inputSelfFilter9;
    QPushButton *selfFilterOkBtn;
    QWidget *MophologyWidget;
    QLabel *label_50;
    QTabWidget *tabWidget_2;
    QWidget *tab;
    QDoubleSpinBox *inputMoph3_0;
    QDoubleSpinBox *inputMoph3_1;
    QDoubleSpinBox *inputMoph3_2;
    QDoubleSpinBox *inputMoph3_3;
    QDoubleSpinBox *inputMoph3_4;
    QDoubleSpinBox *inputMoph3_5;
    QDoubleSpinBox *inputMoph3_6;
    QDoubleSpinBox *inputMoph3_7;
    QDoubleSpinBox *inputMoph3_8;
    QWidget *tab_2;
    QDoubleSpinBox *inputMoph5_0;
    QDoubleSpinBox *inputMoph5_1;
    QDoubleSpinBox *inputMoph5_2;
    QDoubleSpinBox *inputMoph5_3;
    QDoubleSpinBox *inputMoph5_4;
    QDoubleSpinBox *inputMoph5_5;
    QDoubleSpinBox *inputMoph5_6;
    QDoubleSpinBox *inputMoph5_7;
    QDoubleSpinBox *inputMoph5_8;
    QDoubleSpinBox *inputMoph5_9;
    QDoubleSpinBox *inputMoph5_10;
    QDoubleSpinBox *inputMoph5_11;
    QDoubleSpinBox *inputMoph5_12;
    QDoubleSpinBox *inputMoph5_13;
    QDoubleSpinBox *inputMoph5_14;
    QDoubleSpinBox *inputMoph5_15;
    QDoubleSpinBox *inputMoph5_16;
    QDoubleSpinBox *inputMoph5_17;
    QDoubleSpinBox *inputMoph5_18;
    QDoubleSpinBox *inputMoph5_19;
    QDoubleSpinBox *inputMoph5_20;
    QDoubleSpinBox *inputMoph5_21;
    QDoubleSpinBox *inputMoph5_22;
    QDoubleSpinBox *inputMoph5_23;
    QDoubleSpinBox *inputMoph5_24;
    QWidget *tab_3;
    QTextEdit *textEdit;
    QPushButton *dilationBtn;
    QPushButton *erosionBtn;
    QPushButton *openBtn;
    QPushButton *closeBtn;
    QPushButton *thinningBtn;
    QPushButton *thickeningBtn;
    QFrame *line_8;
    QLabel *label_51;
    QPushButton *distanceBtn;
    QPushButton *skeletonBtn;
    QPushButton *SkeletonReconBtn;
    QFrame *line_9;
    QLabel *label_52;
    QPushButton *reconstructionBtn;
    QLabel *label_53;
    QSpinBox *inputAnchorRow;
    QSpinBox *inputAnchorCol;
    QLabel *label_54;
    QLabel *label_55;
    QPushButton *watershedBtn;
    QLabel *label_56;
    QLabel *helpLabel;
    QStatusBar *statusBar;
    QToolBar *mainToolBar;
    QMenuBar *menuBar;
    QMenu *menuFile;
    QMenu *menuEdit;
    QMenu *menucolor_operation;
    QMenu *menuchannel_split;
    QMenu *menubinary_analysis;
    QMenu *menudraw_histogram;
    QMenu *menugrayscale_adjustment;
    QMenu *menufilter;
    QMenu *menuedge_detection;
    QMenu *menusobel;
    QMenu *menuhough;
    QMenu *menuSettings;
    QMenu *menuWindow_mode;

    void setupUi(QMainWindow *miniPSClass)
    {
        if (miniPSClass->objectName().isEmpty())
            miniPSClass->setObjectName(QStringLiteral("miniPSClass"));
        miniPSClass->resize(1920, 980);
        actionopen_image = new QAction(miniPSClass);
        actionopen_image->setObjectName(QStringLiteral("actionopen_image"));
        actionsave_image = new QAction(miniPSClass);
        actionsave_image->setObjectName(QStringLiteral("actionsave_image"));
        actionminimize = new QAction(miniPSClass);
        actionminimize->setObjectName(QStringLiteral("actionminimize"));
        actionundo = new QAction(miniPSClass);
        actionundo->setObjectName(QStringLiteral("actionundo"));
        actionfull_screen = new QAction(miniPSClass);
        actionfull_screen->setObjectName(QStringLiteral("actionfull_screen"));
        actionwindowed = new QAction(miniPSClass);
        actionwindowed->setObjectName(QStringLiteral("actionwindowed"));
        actionexit = new QAction(miniPSClass);
        actionexit->setObjectName(QStringLiteral("actionexit"));
        actionclean_all_layers = new QAction(miniPSClass);
        actionclean_all_layers->setObjectName(QStringLiteral("actionclean_all_layers"));
        actionRGB2GrayScale = new QAction(miniPSClass);
        actionRGB2GrayScale->setObjectName(QStringLiteral("actionRGB2GrayScale"));
        actionRed = new QAction(miniPSClass);
        actionRed->setObjectName(QStringLiteral("actionRed"));
        actionGreen = new QAction(miniPSClass);
        actionGreen->setObjectName(QStringLiteral("actionGreen"));
        actionBlue = new QAction(miniPSClass);
        actionBlue->setObjectName(QStringLiteral("actionBlue"));
        actionHSB = new QAction(miniPSClass);
        actionHSB->setObjectName(QStringLiteral("actionHSB"));
        actionOtus_Algo = new QAction(miniPSClass);
        actionOtus_Algo->setObjectName(QStringLiteral("actionOtus_Algo"));
        actiondouble_threshod = new QAction(miniPSClass);
        actiondouble_threshod->setObjectName(QStringLiteral("actiondouble_threshod"));
        actionresize = new QAction(miniPSClass);
        actionresize->setObjectName(QStringLiteral("actionresize"));
        actionR_hist = new QAction(miniPSClass);
        actionR_hist->setObjectName(QStringLiteral("actionR_hist"));
        actionG_hist = new QAction(miniPSClass);
        actionG_hist->setObjectName(QStringLiteral("actionG_hist"));
        actionB_hist = new QAction(miniPSClass);
        actionB_hist->setObjectName(QStringLiteral("actionB_hist"));
        actionEqualization = new QAction(miniPSClass);
        actionEqualization->setObjectName(QStringLiteral("actionEqualization"));
        actionrotate = new QAction(miniPSClass);
        actionrotate->setObjectName(QStringLiteral("actionrotate"));
        actionlinear = new QAction(miniPSClass);
        actionlinear->setObjectName(QStringLiteral("actionlinear"));
        actionexp_log = new QAction(miniPSClass);
        actionexp_log->setObjectName(QStringLiteral("actionexp_log"));
        actionlogarithm = new QAction(miniPSClass);
        actionlogarithm->setObjectName(QStringLiteral("actionlogarithm"));
        actionfilter_2 = new QAction(miniPSClass);
        actionfilter_2->setObjectName(QStringLiteral("actionfilter_2"));
        action3_3_self_define = new QAction(miniPSClass);
        action3_3_self_define->setObjectName(QStringLiteral("action3_3_self_define"));
        actionlaplace = new QAction(miniPSClass);
        actionlaplace->setObjectName(QStringLiteral("actionlaplace"));
        actioncanny = new QAction(miniPSClass);
        actioncanny->setObjectName(QStringLiteral("actioncanny"));
        actionsobelX = new QAction(miniPSClass);
        actionsobelX->setObjectName(QStringLiteral("actionsobelX"));
        actionsobelY = new QAction(miniPSClass);
        actionsobelY->setObjectName(QStringLiteral("actionsobelY"));
        actionsobelXY = new QAction(miniPSClass);
        actionsobelXY->setObjectName(QStringLiteral("actionsobelXY"));
        actiongrayscale_mophology = new QAction(miniPSClass);
        actiongrayscale_mophology->setObjectName(QStringLiteral("actiongrayscale_mophology"));
        actionhoughLine = new QAction(miniPSClass);
        actionhoughLine->setObjectName(QStringLiteral("actionhoughLine"));
        actionhoughCircle = new QAction(miniPSClass);
        actionhoughCircle->setObjectName(QStringLiteral("actionhoughCircle"));
        actiondilation = new QAction(miniPSClass);
        actiondilation->setObjectName(QStringLiteral("actiondilation"));
        actionerosion = new QAction(miniPSClass);
        actionerosion->setObjectName(QStringLiteral("actionerosion"));
        actionopen = new QAction(miniPSClass);
        actionopen->setObjectName(QStringLiteral("actionopen"));
        actionclose = new QAction(miniPSClass);
        actionclose->setObjectName(QStringLiteral("actionclose"));
        actionthinning_binary = new QAction(miniPSClass);
        actionthinning_binary->setObjectName(QStringLiteral("actionthinning_binary"));
        actionthickening_binary_only = new QAction(miniPSClass);
        actionthickening_binary_only->setObjectName(QStringLiteral("actionthickening_binary_only"));
        actiondistance_transform_binary_only = new QAction(miniPSClass);
        actiondistance_transform_binary_only->setObjectName(QStringLiteral("actiondistance_transform_binary_only"));
        actionskeleton_binary_only = new QAction(miniPSClass);
        actionskeleton_binary_only->setObjectName(QStringLiteral("actionskeleton_binary_only"));
        actionskeleton_reconstruction_binary_only = new QAction(miniPSClass);
        actionskeleton_reconstruction_binary_only->setObjectName(QStringLiteral("actionskeleton_reconstruction_binary_only"));
        actionwatershed = new QAction(miniPSClass);
        actionwatershed->setObjectName(QStringLiteral("actionwatershed"));
        actionbinary = new QAction(miniPSClass);
        actionbinary->setObjectName(QStringLiteral("actionbinary"));
        actiongrayscale = new QAction(miniPSClass);
        actiongrayscale->setObjectName(QStringLiteral("actiongrayscale"));
        actionmophology = new QAction(miniPSClass);
        actionmophology->setObjectName(QStringLiteral("actionmophology"));
        actionDocument = new QAction(miniPSClass);
        actionDocument->setObjectName(QStringLiteral("actionDocument"));
        centralWidget = new QWidget(miniPSClass);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        exitBtn = new QPushButton(centralWidget);
        exitBtn->setObjectName(QStringLiteral("exitBtn"));
        exitBtn->setGeometry(QRect(2340, 0, 112, 34));
        exitBtn->setCheckable(false);
        exitBtn->setAutoDefault(false);
        exitBtn->setFlat(false);
        groupBox = new QGroupBox(centralWidget);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(1430, 70, 461, 331));
        groupBox->setCursor(QCursor(Qt::ArrowCursor));
        line = new QFrame(groupBox);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(17, 240, 431, 20));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(groupBox);
        line_2->setObjectName(QStringLiteral("line_2"));
        line_2->setGeometry(QRect(330, 30, 20, 201));
        line_2->setFrameShape(QFrame::VLine);
        line_2->setFrameShadow(QFrame::Sunken);
        horizontalSlider = new QSlider(groupBox);
        horizontalSlider->setObjectName(QStringLiteral("horizontalSlider"));
        horizontalSlider->setGeometry(QRect(80, 280, 301, 22));
        horizontalSlider->setCursor(QCursor(Qt::ClosedHandCursor));
        horizontalSlider->setOrientation(Qt::Horizontal);
        zoomOutBtn = new QPushButton(groupBox);
        zoomOutBtn->setObjectName(QStringLiteral("zoomOutBtn"));
        zoomOutBtn->setGeometry(QRect(50, 273, 34, 34));
        zoomOutBtn->setCursor(QCursor(Qt::PointingHandCursor));
        zoomInBtn = new QPushButton(groupBox);
        zoomInBtn->setObjectName(QStringLiteral("zoomInBtn"));
        zoomInBtn->setGeometry(QRect(380, 273, 34, 34));
        zoomInBtn->setCursor(QCursor(Qt::PointingHandCursor));
        label_scaleVal = new QLabel(groupBox);
        label_scaleVal->setObjectName(QStringLiteral("label_scaleVal"));
        label_scaleVal->setGeometry(QRect(210, 300, 81, 18));
        label = new QLabel(groupBox);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(350, 60, 31, 16));
        label_2 = new QLabel(groupBox);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(350, 90, 21, 18));
        label_3 = new QLabel(groupBox);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(350, 140, 21, 18));
        label_4 = new QLabel(groupBox);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(350, 170, 16, 18));
        label_posX = new QLabel(groupBox);
        label_posX->setObjectName(QStringLiteral("label_posX"));
        label_posX->setGeometry(QRect(370, 60, 81, 18));
        label_posY = new QLabel(groupBox);
        label_posY->setObjectName(QStringLiteral("label_posY"));
        label_posY->setGeometry(QRect(370, 90, 81, 18));
        label_width = new QLabel(groupBox);
        label_width->setObjectName(QStringLiteral("label_width"));
        label_width->setGeometry(QRect(370, 140, 81, 18));
        label_height = new QLabel(groupBox);
        label_height->setObjectName(QStringLiteral("label_height"));
        label_height->setGeometry(QRect(370, 170, 81, 18));
        label_5 = new QLabel(groupBox);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(70, 60, 41, 18));
        label_6 = new QLabel(groupBox);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(70, 100, 31, 18));
        label_7 = new QLabel(groupBox);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(70, 140, 31, 18));
        label_rVal = new QLabel(groupBox);
        label_rVal->setObjectName(QStringLiteral("label_rVal"));
        label_rVal->setGeometry(QRect(100, 60, 81, 18));
        label_gVal = new QLabel(groupBox);
        label_gVal->setObjectName(QStringLiteral("label_gVal"));
        label_gVal->setGeometry(QRect(100, 100, 81, 18));
        label_bVal = new QLabel(groupBox);
        label_bVal->setObjectName(QStringLiteral("label_bVal"));
        label_bVal->setGeometry(QRect(100, 140, 81, 18));
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(170, 40, 1212, 863));
        layer1 = new QWidget();
        layer1->setObjectName(QStringLiteral("layer1"));
        scrollArea = new QScrollArea(layer1);
        scrollArea->setObjectName(QStringLiteral("scrollArea"));
        scrollArea->setGeometry(QRect(0, 0, 1212, 834));
        scrollArea->setMinimumSize(QSize(0, 0));
        scrollArea->viewport()->setProperty("cursor", QVariant(QCursor(Qt::CrossCursor)));
        scrollArea->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        scrollArea->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        scrollArea->setWidgetResizable(true);
        scrollAreaWidgetContents = new QWidget();
        scrollAreaWidgetContents->setObjectName(QStringLiteral("scrollAreaWidgetContents"));
        scrollAreaWidgetContents->setGeometry(QRect(0, 0, 1184, 806));
        scrollArea->setWidget(scrollAreaWidgetContents);
        tabWidget->addTab(layer1, QString());
        layer2 = new QWidget();
        layer2->setObjectName(QStringLiteral("layer2"));
        scrollArea_2 = new QScrollArea(layer2);
        scrollArea_2->setObjectName(QStringLiteral("scrollArea_2"));
        scrollArea_2->setGeometry(QRect(0, 0, 1212, 834));
        scrollArea_2->setMinimumSize(QSize(0, 0));
        scrollArea_2->viewport()->setProperty("cursor", QVariant(QCursor(Qt::CrossCursor)));
        scrollArea_2->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        scrollArea_2->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        scrollArea_2->setWidgetResizable(true);
        scrollAreaWidgetContents_2 = new QWidget();
        scrollAreaWidgetContents_2->setObjectName(QStringLiteral("scrollAreaWidgetContents_2"));
        scrollAreaWidgetContents_2->setGeometry(QRect(0, 0, 1184, 806));
        scrollArea_2->setWidget(scrollAreaWidgetContents_2);
        tabWidget->addTab(layer2, QString());
        layer3 = new QWidget();
        layer3->setObjectName(QStringLiteral("layer3"));
        scrollArea_3 = new QScrollArea(layer3);
        scrollArea_3->setObjectName(QStringLiteral("scrollArea_3"));
        scrollArea_3->setGeometry(QRect(0, 0, 1212, 834));
        scrollArea_3->setMinimumSize(QSize(0, 0));
        scrollArea_3->viewport()->setProperty("cursor", QVariant(QCursor(Qt::CrossCursor)));
        scrollArea_3->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        scrollArea_3->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        scrollArea_3->setWidgetResizable(true);
        scrollAreaWidgetContents_3 = new QWidget();
        scrollAreaWidgetContents_3->setObjectName(QStringLiteral("scrollAreaWidgetContents_3"));
        scrollAreaWidgetContents_3->setGeometry(QRect(0, 0, 1184, 806));
        scrollArea_3->setWidget(scrollAreaWidgetContents_3);
        tabWidget->addTab(layer3, QString());
        layer4 = new QWidget();
        layer4->setObjectName(QStringLiteral("layer4"));
        scrollArea_4 = new QScrollArea(layer4);
        scrollArea_4->setObjectName(QStringLiteral("scrollArea_4"));
        scrollArea_4->setGeometry(QRect(0, 0, 1212, 834));
        scrollArea_4->setMinimumSize(QSize(0, 0));
        scrollArea_4->viewport()->setProperty("cursor", QVariant(QCursor(Qt::CrossCursor)));
        scrollArea_4->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        scrollArea_4->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        scrollArea_4->setWidgetResizable(true);
        scrollAreaWidgetContents_4 = new QWidget();
        scrollAreaWidgetContents_4->setObjectName(QStringLiteral("scrollAreaWidgetContents_4"));
        scrollAreaWidgetContents_4->setGeometry(QRect(0, 0, 1184, 806));
        scrollArea_4->setWidget(scrollAreaWidgetContents_4);
        tabWidget->addTab(layer4, QString());
        layer5 = new QWidget();
        layer5->setObjectName(QStringLiteral("layer5"));
        scrollArea_5 = new QScrollArea(layer5);
        scrollArea_5->setObjectName(QStringLiteral("scrollArea_5"));
        scrollArea_5->setGeometry(QRect(0, 0, 1212, 834));
        scrollArea_5->setMinimumSize(QSize(0, 0));
        scrollArea_5->viewport()->setProperty("cursor", QVariant(QCursor(Qt::CrossCursor)));
        scrollArea_5->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        scrollArea_5->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        scrollArea_5->setWidgetResizable(true);
        scrollAreaWidgetContents_5 = new QWidget();
        scrollAreaWidgetContents_5->setObjectName(QStringLiteral("scrollAreaWidgetContents_5"));
        scrollAreaWidgetContents_5->setGeometry(QRect(0, 0, 1184, 806));
        scrollArea_5->setWidget(scrollAreaWidgetContents_5);
        tabWidget->addTab(layer5, QString());
        label_imagesize = new QLabel(centralWidget);
        label_imagesize->setObjectName(QStringLiteral("label_imagesize"));
        label_imagesize->setGeometry(QRect(1230, 48, 151, 18));
        leftToolBar = new QWidget(centralWidget);
        leftToolBar->setObjectName(QStringLiteral("leftToolBar"));
        leftToolBar->setGeometry(QRect(30, 70, 131, 691));
        normalModeBtn = new QPushButton(leftToolBar);
        normalModeBtn->setObjectName(QStringLiteral("normalModeBtn"));
        normalModeBtn->setGeometry(QRect(10, 10, 51, 51));
        normalModeBtn->setCursor(QCursor(Qt::PointingHandCursor));
        normalModeBtn->setStyleSheet(QLatin1String("\n"
"border-image: url(:/miniPS/Resources/browse.png);\n"
"background-color: rgb(225, 225, 225);"));
        slctModeBtn = new QPushButton(leftToolBar);
        slctModeBtn->setObjectName(QStringLiteral("slctModeBtn"));
        slctModeBtn->setGeometry(QRect(70, 10, 51, 51));
        slctModeBtn->setCursor(QCursor(Qt::PointingHandCursor));
        slctModeBtn->setStyleSheet(QLatin1String("border-image: url(:/miniPS/Resources/select.png);\n"
"selection-background-color: rgb(170, 255, 255);\n"
"background-color: rgb(225, 225, 225);\n"
""));
        pushButton = new QPushButton(leftToolBar);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(10, 70, 51, 51));
        pushButton->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton->setStyleSheet(QLatin1String("border-image: url(:/miniPS/Resources/pen.png);\n"
"background-color: rgb(225, 225, 225);"));
        pushButton_2 = new QPushButton(leftToolBar);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(70, 70, 51, 51));
        pushButton_2->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_2->setStyleSheet(QLatin1String("border-image: url(:/miniPS/Resources/im-eraser.png);\n"
"background-color: rgb(225, 225, 225);"));
        line_3 = new QFrame(leftToolBar);
        line_3->setObjectName(QStringLiteral("line_3"));
        line_3->setGeometry(QRect(0, 550, 131, 20));
        line_3->setFrameShape(QFrame::HLine);
        line_3->setFrameShadow(QFrame::Sunken);
        picked_color1 = new QLabel(leftToolBar);
        picked_color1->setObjectName(QStringLiteral("picked_color1"));
        picked_color1->setGeometry(QRect(20, 570, 51, 51));
        picked_color2 = new QLabel(leftToolBar);
        picked_color2->setObjectName(QStringLiteral("picked_color2"));
        picked_color2->setGeometry(QRect(60, 610, 51, 51));
        colorSwitchBtn = new QPushButton(leftToolBar);
        colorSwitchBtn->setObjectName(QStringLiteral("colorSwitchBtn"));
        colorSwitchBtn->setGeometry(QRect(80, 570, 31, 34));
        colorSwitchBtn->setStyleSheet(QLatin1String("border-image: url(:/miniPS/Resources/exchange.png);\n"
"background-color: rgb(225, 225, 225);"));
        colorResetBtn = new QPushButton(leftToolBar);
        colorResetBtn->setObjectName(QStringLiteral("colorResetBtn"));
        colorResetBtn->setGeometry(QRect(10, 630, 31, 34));
        colorResetBtn->setStyleSheet(QLatin1String("border-image: url(:/miniPS/Resources/reset.png);\n"
"background-color: rgb(225, 225, 225);"));
        getColorBtn = new QPushButton(leftToolBar);
        getColorBtn->setObjectName(QStringLiteral("getColorBtn"));
        getColorBtn->setGeometry(QRect(70, 250, 51, 51));
        getColorBtn->setCursor(QCursor(Qt::PointingHandCursor));
        getColorBtn->setStyleSheet(QLatin1String("border-image: url(:/miniPS/Resources/pick.png);\n"
"background-color: rgb(225, 225, 225);"));
        cutBtn = new QPushButton(leftToolBar);
        cutBtn->setObjectName(QStringLiteral("cutBtn"));
        cutBtn->setGeometry(QRect(10, 130, 51, 51));
        cutBtn->setCursor(QCursor(Qt::PointingHandCursor));
        cutBtn->setStyleSheet(QLatin1String("border-image: url(:/miniPS/Resources/cut.png);\n"
"background-color: rgb(225, 225, 225);"));
        addBtn = new QPushButton(leftToolBar);
        addBtn->setObjectName(QStringLiteral("addBtn"));
        addBtn->setGeometry(QRect(10, 190, 51, 51));
        addBtn->setCursor(QCursor(Qt::PointingHandCursor));
        addBtn->setStyleSheet(QLatin1String("border-image: url(:/miniPS/Resources/add.png);\n"
"background-color: rgb(225, 225, 225);"));
        subtractionBtn = new QPushButton(leftToolBar);
        subtractionBtn->setObjectName(QStringLiteral("subtractionBtn"));
        subtractionBtn->setGeometry(QRect(70, 190, 51, 51));
        subtractionBtn->setCursor(QCursor(Qt::PointingHandCursor));
        subtractionBtn->setStyleSheet(QLatin1String("border-image: url(:/miniPS/Resources/sub.png);\n"
"background-color: rgb(225, 225, 225);"));
        multiplicationBtn = new QPushButton(leftToolBar);
        multiplicationBtn->setObjectName(QStringLiteral("multiplicationBtn"));
        multiplicationBtn->setGeometry(QRect(10, 250, 51, 51));
        multiplicationBtn->setCursor(QCursor(Qt::PointingHandCursor));
        multiplicationBtn->setStyleSheet(QLatin1String("border-image: url(:/miniPS/Resources/multiply.png);\n"
"background-color: rgb(225, 225, 225);"));
        spinBtn = new QPushButton(leftToolBar);
        spinBtn->setObjectName(QStringLiteral("spinBtn"));
        spinBtn->setGeometry(QRect(70, 130, 51, 51));
        spinBtn->setCursor(QCursor(Qt::PointingHandCursor));
        spinBtn->setStyleSheet(QLatin1String("border-image: url(:/miniPS/Resources/rotate.png);\n"
"background-color: rgb(225, 225, 225);"));
        helloWorldBtn = new QPushButton(leftToolBar);
        helloWorldBtn->setObjectName(QStringLiteral("helloWorldBtn"));
        helloWorldBtn->setGeometry(QRect(10, 310, 112, 241));
        line_4 = new QFrame(centralWidget);
        line_4->setObjectName(QStringLiteral("line_4"));
        line_4->setGeometry(QRect(30, 60, 131, 20));
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        line_6 = new QFrame(centralWidget);
        line_6->setObjectName(QStringLiteral("line_6"));
        line_6->setGeometry(QRect(30, 750, 131, 16));
        line_6->setFrameShape(QFrame::HLine);
        line_6->setFrameShadow(QFrame::Sunken);
        line_7 = new QFrame(centralWidget);
        line_7->setObjectName(QStringLiteral("line_7"));
        line_7->setGeometry(QRect(150, 70, 16, 691));
        line_7->setFrameShape(QFrame::VLine);
        line_7->setFrameShadow(QFrame::Sunken);
        line_5 = new QFrame(centralWidget);
        line_5->setObjectName(QStringLiteral("line_5"));
        line_5->setGeometry(QRect(18, 70, 20, 691));
        line_5->setFrameShape(QFrame::VLine);
        line_5->setFrameShadow(QFrame::Sunken);
        containerWidget = new QWidget(centralWidget);
        containerWidget->setObjectName(QStringLiteral("containerWidget"));
        containerWidget->setGeometry(QRect(1430, 430, 461, 471));
        hsvWidget = new QWidget(containerWidget);
        hsvWidget->setObjectName(QStringLiteral("hsvWidget"));
        hsvWidget->setGeometry(QRect(10, 10, 441, 241));
        horizontalSlider_h = new QSlider(hsvWidget);
        horizontalSlider_h->setObjectName(QStringLiteral("horizontalSlider_h"));
        horizontalSlider_h->setGeometry(QRect(80, 30, 291, 22));
        horizontalSlider_h->setOrientation(Qt::Horizontal);
        horizontalSlider_s = new QSlider(hsvWidget);
        horizontalSlider_s->setObjectName(QStringLiteral("horizontalSlider_s"));
        horizontalSlider_s->setGeometry(QRect(80, 90, 291, 22));
        horizontalSlider_s->setOrientation(Qt::Horizontal);
        horizontalSlider_v = new QSlider(hsvWidget);
        horizontalSlider_v->setObjectName(QStringLiteral("horizontalSlider_v"));
        horizontalSlider_v->setGeometry(QRect(80, 150, 291, 22));
        horizontalSlider_v->setOrientation(Qt::Horizontal);
        label_9 = new QLabel(hsvWidget);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(50, 30, 31, 18));
        label_10 = new QLabel(hsvWidget);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(50, 90, 16, 18));
        label_11 = new QLabel(hsvWidget);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(50, 150, 16, 18));
        HSVokBtn = new QPushButton(hsvWidget);
        HSVokBtn->setObjectName(QStringLiteral("HSVokBtn"));
        HSVokBtn->setGeometry(QRect(280, 190, 112, 34));
        doubleThreshodWidget = new QWidget(containerWidget);
        doubleThreshodWidget->setObjectName(QStringLiteral("doubleThreshodWidget"));
        doubleThreshodWidget->setGeometry(QRect(10, 10, 441, 171));
        inputThreshod1 = new QSpinBox(doubleThreshodWidget);
        inputThreshod1->setObjectName(QStringLiteral("inputThreshod1"));
        inputThreshod1->setGeometry(QRect(120, 30, 49, 25));
        inputThreshod1->setMaximum(255);
        label_12 = new QLabel(doubleThreshodWidget);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(20, 33, 101, 18));
        label_13 = new QLabel(doubleThreshodWidget);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(200, 33, 111, 18));
        inputThreshod2 = new QSpinBox(doubleThreshodWidget);
        inputThreshod2->setObjectName(QStringLiteral("inputThreshod2"));
        inputThreshod2->setGeometry(QRect(310, 30, 49, 25));
        inputThreshod2->setMaximum(255);
        doubleThreshodOkBtn = new QPushButton(doubleThreshodWidget);
        doubleThreshodOkBtn->setObjectName(QStringLiteral("doubleThreshodOkBtn"));
        doubleThreshodOkBtn->setGeometry(QRect(310, 100, 112, 34));
        addWidget = new QWidget(containerWidget);
        addWidget->setObjectName(QStringLiteral("addWidget"));
        addWidget->setGeometry(QRect(10, 10, 441, 241));
        label_8 = new QLabel(addWidget);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(40, 30, 161, 18));
        label_14 = new QLabel(addWidget);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(50, 70, 81, 18));
        label_15 = new QLabel(addWidget);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(50, 110, 81, 18));
        label_16 = new QLabel(addWidget);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(220, 70, 81, 18));
        label_17 = new QLabel(addWidget);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(220, 110, 81, 18));
        inputAddImg1 = new QSpinBox(addWidget);
        inputAddImg1->setObjectName(QStringLiteral("inputAddImg1"));
        inputAddImg1->setGeometry(QRect(130, 70, 49, 25));
        inputAddImg1->setMinimum(1);
        inputAddImg1->setMaximum(5);
        inputAddImg2 = new QSpinBox(addWidget);
        inputAddImg2->setObjectName(QStringLiteral("inputAddImg2"));
        inputAddImg2->setGeometry(QRect(130, 110, 49, 25));
        inputAddImg2->setMinimum(1);
        inputAddImg2->setMaximum(5);
        addOkBtn = new QPushButton(addWidget);
        addOkBtn->setObjectName(QStringLiteral("addOkBtn"));
        addOkBtn->setGeometry(QRect(270, 190, 112, 34));
        inputAddWeight1 = new QDoubleSpinBox(addWidget);
        inputAddWeight1->setObjectName(QStringLiteral("inputAddWeight1"));
        inputAddWeight1->setGeometry(QRect(290, 70, 76, 25));
        inputAddWeight1->setMaximum(1);
        inputAddWeight2 = new QDoubleSpinBox(addWidget);
        inputAddWeight2->setObjectName(QStringLiteral("inputAddWeight2"));
        inputAddWeight2->setGeometry(QRect(290, 110, 76, 25));
        inputAddWeight2->setMaximum(1);
        label_18 = new QLabel(addWidget);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(50, 150, 81, 18));
        label_19 = new QLabel(addWidget);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(220, 150, 81, 18));
        inputAddX = new QSpinBox(addWidget);
        inputAddX->setObjectName(QStringLiteral("inputAddX"));
        inputAddX->setGeometry(QRect(130, 150, 49, 25));
        inputAddX->setMaximum(99999);
        inputAddY = new QSpinBox(addWidget);
        inputAddY->setObjectName(QStringLiteral("inputAddY"));
        inputAddY->setGeometry(QRect(290, 150, 49, 25));
        inputAddY->setMaximum(99999);
        subtractionWidget = new QWidget(containerWidget);
        subtractionWidget->setObjectName(QStringLiteral("subtractionWidget"));
        subtractionWidget->setGeometry(QRect(10, 10, 441, 241));
        label_20 = new QLabel(subtractionWidget);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(30, 30, 151, 18));
        label_21 = new QLabel(subtractionWidget);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(50, 70, 81, 18));
        label_22 = new QLabel(subtractionWidget);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(50, 110, 81, 18));
        label_23 = new QLabel(subtractionWidget);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(50, 150, 81, 18));
        label_24 = new QLabel(subtractionWidget);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(220, 150, 81, 18));
        inputSubImg1 = new QSpinBox(subtractionWidget);
        inputSubImg1->setObjectName(QStringLiteral("inputSubImg1"));
        inputSubImg1->setGeometry(QRect(130, 70, 49, 25));
        inputSubImg1->setMinimum(1);
        inputSubImg1->setMaximum(5);
        inputSub2 = new QSpinBox(subtractionWidget);
        inputSub2->setObjectName(QStringLiteral("inputSub2"));
        inputSub2->setGeometry(QRect(130, 110, 49, 25));
        inputSub2->setMinimum(1);
        inputSub2->setMaximum(5);
        inputSubX = new QSpinBox(subtractionWidget);
        inputSubX->setObjectName(QStringLiteral("inputSubX"));
        inputSubX->setGeometry(QRect(130, 150, 49, 25));
        inputSubX->setMaximum(99999);
        inputSubY = new QSpinBox(subtractionWidget);
        inputSubY->setObjectName(QStringLiteral("inputSubY"));
        inputSubY->setGeometry(QRect(280, 150, 49, 25));
        inputSubY->setMaximum(99999);
        substractionOkBtn = new QPushButton(subtractionWidget);
        substractionOkBtn->setObjectName(QStringLiteral("substractionOkBtn"));
        substractionOkBtn->setGeometry(QRect(260, 190, 112, 34));
        multiplicationWidget = new QWidget(containerWidget);
        multiplicationWidget->setObjectName(QStringLiteral("multiplicationWidget"));
        multiplicationWidget->setGeometry(QRect(10, 10, 441, 181));
        label_25 = new QLabel(multiplicationWidget);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(30, 30, 151, 18));
        label_26 = new QLabel(multiplicationWidget);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(30, 70, 81, 18));
        label_27 = new QLabel(multiplicationWidget);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(210, 70, 81, 18));
        inputMultiImg1 = new QSpinBox(multiplicationWidget);
        inputMultiImg1->setObjectName(QStringLiteral("inputMultiImg1"));
        inputMultiImg1->setGeometry(QRect(110, 70, 49, 25));
        inputMultiImg1->setMinimum(1);
        inputMultiImg1->setMaximum(5);
        inputMultiImg2 = new QSpinBox(multiplicationWidget);
        inputMultiImg2->setObjectName(QStringLiteral("inputMultiImg2"));
        inputMultiImg2->setGeometry(QRect(290, 70, 49, 25));
        inputMultiImg2->setMinimum(1);
        inputMultiImg2->setMaximum(5);
        multiplicationOkBtn = new QPushButton(multiplicationWidget);
        multiplicationOkBtn->setObjectName(QStringLiteral("multiplicationOkBtn"));
        multiplicationOkBtn->setGeometry(QRect(270, 120, 112, 34));
        divisionWidget = new QWidget(containerWidget);
        divisionWidget->setObjectName(QStringLiteral("divisionWidget"));
        divisionWidget->setGeometry(QRect(10, 10, 441, 181));
        label_28 = new QLabel(divisionWidget);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(30, 30, 151, 18));
        label_29 = new QLabel(divisionWidget);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(30, 70, 81, 18));
        label_30 = new QLabel(divisionWidget);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(210, 70, 81, 18));
        inputDvdImg1 = new QSpinBox(divisionWidget);
        inputDvdImg1->setObjectName(QStringLiteral("inputDvdImg1"));
        inputDvdImg1->setGeometry(QRect(110, 70, 49, 25));
        inputDvdImg1->setMinimum(1);
        inputDvdImg1->setMaximum(5);
        inputDvdImg2 = new QSpinBox(divisionWidget);
        inputDvdImg2->setObjectName(QStringLiteral("inputDvdImg2"));
        inputDvdImg2->setGeometry(QRect(290, 70, 49, 25));
        inputDvdImg2->setMinimum(1);
        inputDvdImg2->setMaximum(5);
        divisionOkBtn = new QPushButton(divisionWidget);
        divisionOkBtn->setObjectName(QStringLiteral("divisionOkBtn"));
        divisionOkBtn->setGeometry(QRect(270, 120, 112, 34));
        resizeWidget = new QWidget(containerWidget);
        resizeWidget->setObjectName(QStringLiteral("resizeWidget"));
        resizeWidget->setGeometry(QRect(10, 10, 441, 200));
        label_31 = new QLabel(resizeWidget);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(30, 20, 81, 18));
        inputChoiceLINEAR = new QCheckBox(resizeWidget);
        inputChoiceLINEAR->setObjectName(QStringLiteral("inputChoiceLINEAR"));
        inputChoiceLINEAR->setGeometry(QRect(230, 110, 105, 22));
        inputChoiceNN = new QCheckBox(resizeWidget);
        inputChoiceNN->setObjectName(QStringLiteral("inputChoiceNN"));
        inputChoiceNN->setGeometry(QRect(40, 110, 105, 22));
        label_32 = new QLabel(resizeWidget);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(40, 70, 61, 18));
        inputResizeWidth = new QSpinBox(resizeWidget);
        inputResizeWidth->setObjectName(QStringLiteral("inputResizeWidth"));
        inputResizeWidth->setGeometry(QRect(110, 70, 49, 25));
        inputResizeWidth->setMinimum(1);
        inputResizeWidth->setMaximum(9999);
        label_33 = new QLabel(resizeWidget);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(230, 70, 71, 18));
        inputResizeHeight = new QSpinBox(resizeWidget);
        inputResizeHeight->setObjectName(QStringLiteral("inputResizeHeight"));
        inputResizeHeight->setGeometry(QRect(310, 70, 49, 25));
        inputResizeHeight->setMinimum(1);
        inputResizeHeight->setMaximum(99999);
        resizeOkBtn = new QPushButton(resizeWidget);
        resizeOkBtn->setObjectName(QStringLiteral("resizeOkBtn"));
        resizeOkBtn->setGeometry(QRect(270, 150, 131, 34));
        filterWidget = new QWidget(containerWidget);
        filterWidget->setObjectName(QStringLiteral("filterWidget"));
        filterWidget->setGeometry(QRect(10, 10, 441, 241));
        label_34 = new QLabel(filterWidget);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(30, 30, 81, 18));
        inputFilterChoiceBox = new QCheckBox(filterWidget);
        inputFilterChoiceBox->setObjectName(QStringLiteral("inputFilterChoiceBox"));
        inputFilterChoiceBox->setGeometry(QRect(50, 70, 105, 22));
        inputFilterChoiceMedian = new QCheckBox(filterWidget);
        inputFilterChoiceMedian->setObjectName(QStringLiteral("inputFilterChoiceMedian"));
        inputFilterChoiceMedian->setGeometry(QRect(50, 110, 105, 22));
        inputFilterChoiceGaussian = new QCheckBox(filterWidget);
        inputFilterChoiceGaussian->setObjectName(QStringLiteral("inputFilterChoiceGaussian"));
        inputFilterChoiceGaussian->setGeometry(QRect(50, 150, 105, 22));
        label_35 = new QLabel(filterWidget);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(200, 70, 111, 18));
        inputKernelSize = new QSpinBox(filterWidget);
        inputKernelSize->setObjectName(QStringLiteral("inputKernelSize"));
        inputKernelSize->setGeometry(QRect(320, 70, 49, 25));
        inputKernelSize->setMinimum(3);
        inputKernelSize->setMaximum(25);
        inputKernelSize->setSingleStep(2);
        filterOkBtn = new QPushButton(filterWidget);
        filterOkBtn->setObjectName(QStringLiteral("filterOkBtn"));
        filterOkBtn->setGeometry(QRect(260, 140, 112, 34));
        rotateWidget = new QWidget(containerWidget);
        rotateWidget->setObjectName(QStringLiteral("rotateWidget"));
        rotateWidget->setGeometry(QRect(10, 10, 441, 231));
        label_36 = new QLabel(rotateWidget);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(30, 30, 81, 18));
        inputRotateTheta = new QDoubleSpinBox(rotateWidget);
        inputRotateTheta->setObjectName(QStringLiteral("inputRotateTheta"));
        inputRotateTheta->setGeometry(QRect(140, 80, 76, 25));
        inputRotateTheta->setMaximum(359.99);
        label_37 = new QLabel(rotateWidget);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(80, 80, 81, 18));
        rotateOkBtn = new QPushButton(rotateWidget);
        rotateOkBtn->setObjectName(QStringLiteral("rotateOkBtn"));
        rotateOkBtn->setGeometry(QRect(250, 160, 112, 34));
        inputRotateChoiceNN = new QCheckBox(rotateWidget);
        inputRotateChoiceNN->setObjectName(QStringLiteral("inputRotateChoiceNN"));
        inputRotateChoiceNN->setGeometry(QRect(80, 130, 105, 22));
        inputRotateChoiceLINEAR = new QCheckBox(rotateWidget);
        inputRotateChoiceLINEAR->setObjectName(QStringLiteral("inputRotateChoiceLINEAR"));
        inputRotateChoiceLINEAR->setGeometry(QRect(250, 130, 105, 22));
        label_38 = new QLabel(rotateWidget);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(220, 80, 81, 18));
        GSAWidget = new QWidget(containerWidget);
        GSAWidget->setObjectName(QStringLiteral("GSAWidget"));
        GSAWidget->setGeometry(QRect(10, 10, 441, 411));
        label_39 = new QLabel(GSAWidget);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(30, 40, 311, 18));
        GSASliderD = new QSlider(GSAWidget);
        GSASliderD->setObjectName(QStringLiteral("GSASliderD"));
        GSASliderD->setGeometry(QRect(30, 80, 22, 231));
        GSASliderD->setOrientation(Qt::Vertical);
        GSASliderC = new QSlider(GSAWidget);
        GSASliderC->setObjectName(QStringLiteral("GSASliderC"));
        GSASliderC->setGeometry(QRect(60, 80, 22, 231));
        GSASliderC->setOrientation(Qt::Vertical);
        GSASliderA = new QSlider(GSAWidget);
        GSASliderA->setObjectName(QStringLiteral("GSASliderA"));
        GSASliderA->setGeometry(QRect(90, 320, 241, 22));
        GSASliderA->setOrientation(Qt::Horizontal);
        GSASliderB = new QSlider(GSAWidget);
        GSASliderB->setObjectName(QStringLiteral("GSASliderB"));
        GSASliderB->setGeometry(QRect(90, 350, 241, 22));
        GSASliderB->setOrientation(Qt::Horizontal);
        label_40 = new QLabel(GSAWidget);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(90, 60, 256, 256));
        GSALinearOkBtn = new QPushButton(GSAWidget);
        GSALinearOkBtn->setObjectName(QStringLiteral("GSALinearOkBtn"));
        GSALinearOkBtn->setGeometry(QRect(220, 370, 141, 34));
        label_41 = new QLabel(GSAWidget);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(30, 310, 16, 18));
        label_42 = new QLabel(GSAWidget);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(60, 310, 16, 18));
        label_43 = new QLabel(GSAWidget);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(80, 320, 16, 18));
        label_44 = new QLabel(GSAWidget);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(80, 350, 16, 18));
        inputLinearGSAChoiceRGB = new QCheckBox(GSAWidget);
        inputLinearGSAChoiceRGB->setObjectName(QStringLiteral("inputLinearGSAChoiceRGB"));
        inputLinearGSAChoiceRGB->setGeometry(QRect(360, 70, 81, 22));
        inputLinearGSAChoiceR = new QCheckBox(GSAWidget);
        inputLinearGSAChoiceR->setObjectName(QStringLiteral("inputLinearGSAChoiceR"));
        inputLinearGSAChoiceR->setGeometry(QRect(360, 110, 61, 22));
        inputLinearGSAChoiceG = new QCheckBox(GSAWidget);
        inputLinearGSAChoiceG->setObjectName(QStringLiteral("inputLinearGSAChoiceG"));
        inputLinearGSAChoiceG->setGeometry(QRect(360, 150, 71, 22));
        inputLinearGSAChoiceB = new QCheckBox(GSAWidget);
        inputLinearGSAChoiceB->setObjectName(QStringLiteral("inputLinearGSAChoiceB"));
        inputLinearGSAChoiceB->setGeometry(QRect(360, 190, 61, 22));
        UGSAWidget = new QWidget(containerWidget);
        UGSAWidget->setObjectName(QStringLiteral("UGSAWidget"));
        UGSAWidget->setGeometry(QRect(10, 10, 441, 311));
        label_45 = new QLabel(UGSAWidget);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(20, 30, 281, 18));
        label_46 = new QLabel(UGSAWidget);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(40, 80, 31, 18));
        label_47 = new QLabel(UGSAWidget);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(40, 130, 31, 18));
        label_48 = new QLabel(UGSAWidget);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(40, 180, 31, 18));
        inputUGSAA = new QDoubleSpinBox(UGSAWidget);
        inputUGSAA->setObjectName(QStringLiteral("inputUGSAA"));
        inputUGSAA->setGeometry(QRect(70, 80, 76, 25));
        inputUGSAA->setMaximum(999);
        inputUGSAB = new QDoubleSpinBox(UGSAWidget);
        inputUGSAB->setObjectName(QStringLiteral("inputUGSAB"));
        inputUGSAB->setGeometry(QRect(70, 130, 76, 25));
        inputUGSAB->setMaximum(999);
        inputUGSAC = new QDoubleSpinBox(UGSAWidget);
        inputUGSAC->setObjectName(QStringLiteral("inputUGSAC"));
        inputUGSAC->setGeometry(QRect(70, 180, 76, 25));
        inputUGSAC->setMinimum(0);
        inputUGSAC->setMaximum(999);
        inputUGSAexp = new QCheckBox(UGSAWidget);
        inputUGSAexp->setObjectName(QStringLiteral("inputUGSAexp"));
        inputUGSAexp->setGeometry(QRect(210, 80, 105, 22));
        inputUGSAlog = new QCheckBox(UGSAWidget);
        inputUGSAlog->setObjectName(QStringLiteral("inputUGSAlog"));
        inputUGSAlog->setGeometry(QRect(210, 130, 105, 22));
        UGSAOkBtn = new QPushButton(UGSAWidget);
        UGSAOkBtn->setObjectName(QStringLiteral("UGSAOkBtn"));
        UGSAOkBtn->setGeometry(QRect(250, 230, 112, 34));
        selfFilterWidget = new QWidget(containerWidget);
        selfFilterWidget->setObjectName(QStringLiteral("selfFilterWidget"));
        selfFilterWidget->setGeometry(QRect(10, 10, 441, 331));
        label_49 = new QLabel(selfFilterWidget);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(20, 40, 181, 18));
        inputSelfFilter1 = new QDoubleSpinBox(selfFilterWidget);
        inputSelfFilter1->setObjectName(QStringLiteral("inputSelfFilter1"));
        inputSelfFilter1->setGeometry(QRect(90, 100, 61, 25));
        inputSelfFilter1->setMinimum(-99);
        inputSelfFilter2 = new QDoubleSpinBox(selfFilterWidget);
        inputSelfFilter2->setObjectName(QStringLiteral("inputSelfFilter2"));
        inputSelfFilter2->setGeometry(QRect(150, 100, 61, 25));
        inputSelfFilter2->setMinimum(-99);
        inputSelfFilter3 = new QDoubleSpinBox(selfFilterWidget);
        inputSelfFilter3->setObjectName(QStringLiteral("inputSelfFilter3"));
        inputSelfFilter3->setGeometry(QRect(210, 100, 61, 25));
        inputSelfFilter3->setMinimum(-99);
        inputSelfFilter4 = new QDoubleSpinBox(selfFilterWidget);
        inputSelfFilter4->setObjectName(QStringLiteral("inputSelfFilter4"));
        inputSelfFilter4->setGeometry(QRect(90, 130, 61, 25));
        inputSelfFilter4->setMinimum(-99);
        inputSelfFilter5 = new QDoubleSpinBox(selfFilterWidget);
        inputSelfFilter5->setObjectName(QStringLiteral("inputSelfFilter5"));
        inputSelfFilter5->setGeometry(QRect(150, 130, 61, 25));
        inputSelfFilter5->setMinimum(-99);
        inputSelfFilter6 = new QDoubleSpinBox(selfFilterWidget);
        inputSelfFilter6->setObjectName(QStringLiteral("inputSelfFilter6"));
        inputSelfFilter6->setGeometry(QRect(210, 130, 61, 25));
        inputSelfFilter6->setMinimum(-99);
        inputSelfFilter7 = new QDoubleSpinBox(selfFilterWidget);
        inputSelfFilter7->setObjectName(QStringLiteral("inputSelfFilter7"));
        inputSelfFilter7->setGeometry(QRect(90, 160, 61, 25));
        inputSelfFilter7->setMinimum(-99);
        inputSelfFilter8 = new QDoubleSpinBox(selfFilterWidget);
        inputSelfFilter8->setObjectName(QStringLiteral("inputSelfFilter8"));
        inputSelfFilter8->setGeometry(QRect(150, 160, 61, 25));
        inputSelfFilter8->setMinimum(-99);
        inputSelfFilter9 = new QDoubleSpinBox(selfFilterWidget);
        inputSelfFilter9->setObjectName(QStringLiteral("inputSelfFilter9"));
        inputSelfFilter9->setGeometry(QRect(210, 160, 61, 25));
        inputSelfFilter9->setMinimum(-99);
        selfFilterOkBtn = new QPushButton(selfFilterWidget);
        selfFilterOkBtn->setObjectName(QStringLiteral("selfFilterOkBtn"));
        selfFilterOkBtn->setGeometry(QRect(250, 250, 112, 34));
        MophologyWidget = new QWidget(containerWidget);
        MophologyWidget->setObjectName(QStringLiteral("MophologyWidget"));
        MophologyWidget->setGeometry(QRect(10, 10, 441, 461));
        label_50 = new QLabel(MophologyWidget);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(30, 10, 121, 18));
        tabWidget_2 = new QTabWidget(MophologyWidget);
        tabWidget_2->setObjectName(QStringLiteral("tabWidget_2"));
        tabWidget_2->setGeometry(QRect(10, 30, 421, 191));
        tabWidget_2->setTabPosition(QTabWidget::West);
        tabWidget_2->setTabShape(QTabWidget::Rounded);
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        inputMoph3_0 = new QDoubleSpinBox(tab);
        inputMoph3_0->setObjectName(QStringLiteral("inputMoph3_0"));
        inputMoph3_0->setGeometry(QRect(80, 30, 76, 25));
        inputMoph3_0->setValue(1);
        inputMoph3_1 = new QDoubleSpinBox(tab);
        inputMoph3_1->setObjectName(QStringLiteral("inputMoph3_1"));
        inputMoph3_1->setGeometry(QRect(160, 30, 76, 25));
        inputMoph3_1->setValue(1);
        inputMoph3_2 = new QDoubleSpinBox(tab);
        inputMoph3_2->setObjectName(QStringLiteral("inputMoph3_2"));
        inputMoph3_2->setGeometry(QRect(240, 30, 76, 25));
        inputMoph3_2->setValue(1);
        inputMoph3_3 = new QDoubleSpinBox(tab);
        inputMoph3_3->setObjectName(QStringLiteral("inputMoph3_3"));
        inputMoph3_3->setGeometry(QRect(80, 70, 76, 25));
        inputMoph3_3->setValue(1);
        inputMoph3_4 = new QDoubleSpinBox(tab);
        inputMoph3_4->setObjectName(QStringLiteral("inputMoph3_4"));
        inputMoph3_4->setGeometry(QRect(160, 70, 76, 25));
        inputMoph3_4->setValue(1);
        inputMoph3_5 = new QDoubleSpinBox(tab);
        inputMoph3_5->setObjectName(QStringLiteral("inputMoph3_5"));
        inputMoph3_5->setGeometry(QRect(240, 70, 76, 25));
        inputMoph3_5->setValue(1);
        inputMoph3_6 = new QDoubleSpinBox(tab);
        inputMoph3_6->setObjectName(QStringLiteral("inputMoph3_6"));
        inputMoph3_6->setGeometry(QRect(80, 110, 76, 25));
        inputMoph3_6->setValue(1);
        inputMoph3_7 = new QDoubleSpinBox(tab);
        inputMoph3_7->setObjectName(QStringLiteral("inputMoph3_7"));
        inputMoph3_7->setGeometry(QRect(160, 110, 76, 25));
        inputMoph3_7->setValue(1);
        inputMoph3_8 = new QDoubleSpinBox(tab);
        inputMoph3_8->setObjectName(QStringLiteral("inputMoph3_8"));
        inputMoph3_8->setGeometry(QRect(240, 110, 76, 25));
        inputMoph3_8->setValue(1);
        tabWidget_2->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        inputMoph5_0 = new QDoubleSpinBox(tab_2);
        inputMoph5_0->setObjectName(QStringLiteral("inputMoph5_0"));
        inputMoph5_0->setGeometry(QRect(10, 10, 76, 25));
        inputMoph5_0->setValue(1);
        inputMoph5_1 = new QDoubleSpinBox(tab_2);
        inputMoph5_1->setObjectName(QStringLiteral("inputMoph5_1"));
        inputMoph5_1->setGeometry(QRect(80, 10, 76, 25));
        inputMoph5_1->setValue(1);
        inputMoph5_2 = new QDoubleSpinBox(tab_2);
        inputMoph5_2->setObjectName(QStringLiteral("inputMoph5_2"));
        inputMoph5_2->setGeometry(QRect(150, 10, 76, 25));
        inputMoph5_2->setValue(1);
        inputMoph5_3 = new QDoubleSpinBox(tab_2);
        inputMoph5_3->setObjectName(QStringLiteral("inputMoph5_3"));
        inputMoph5_3->setGeometry(QRect(220, 10, 76, 25));
        inputMoph5_3->setValue(1);
        inputMoph5_4 = new QDoubleSpinBox(tab_2);
        inputMoph5_4->setObjectName(QStringLiteral("inputMoph5_4"));
        inputMoph5_4->setGeometry(QRect(290, 10, 76, 25));
        inputMoph5_4->setValue(1);
        inputMoph5_5 = new QDoubleSpinBox(tab_2);
        inputMoph5_5->setObjectName(QStringLiteral("inputMoph5_5"));
        inputMoph5_5->setGeometry(QRect(10, 40, 76, 25));
        inputMoph5_5->setValue(1);
        inputMoph5_6 = new QDoubleSpinBox(tab_2);
        inputMoph5_6->setObjectName(QStringLiteral("inputMoph5_6"));
        inputMoph5_6->setGeometry(QRect(80, 40, 76, 25));
        inputMoph5_6->setValue(1);
        inputMoph5_7 = new QDoubleSpinBox(tab_2);
        inputMoph5_7->setObjectName(QStringLiteral("inputMoph5_7"));
        inputMoph5_7->setGeometry(QRect(150, 40, 76, 25));
        inputMoph5_7->setValue(1);
        inputMoph5_8 = new QDoubleSpinBox(tab_2);
        inputMoph5_8->setObjectName(QStringLiteral("inputMoph5_8"));
        inputMoph5_8->setGeometry(QRect(220, 40, 76, 25));
        inputMoph5_8->setValue(1);
        inputMoph5_9 = new QDoubleSpinBox(tab_2);
        inputMoph5_9->setObjectName(QStringLiteral("inputMoph5_9"));
        inputMoph5_9->setGeometry(QRect(290, 40, 76, 25));
        inputMoph5_9->setValue(1);
        inputMoph5_10 = new QDoubleSpinBox(tab_2);
        inputMoph5_10->setObjectName(QStringLiteral("inputMoph5_10"));
        inputMoph5_10->setGeometry(QRect(10, 70, 76, 25));
        inputMoph5_10->setValue(1);
        inputMoph5_11 = new QDoubleSpinBox(tab_2);
        inputMoph5_11->setObjectName(QStringLiteral("inputMoph5_11"));
        inputMoph5_11->setGeometry(QRect(80, 70, 76, 25));
        inputMoph5_11->setValue(1);
        inputMoph5_12 = new QDoubleSpinBox(tab_2);
        inputMoph5_12->setObjectName(QStringLiteral("inputMoph5_12"));
        inputMoph5_12->setGeometry(QRect(150, 70, 76, 25));
        inputMoph5_12->setValue(1);
        inputMoph5_13 = new QDoubleSpinBox(tab_2);
        inputMoph5_13->setObjectName(QStringLiteral("inputMoph5_13"));
        inputMoph5_13->setGeometry(QRect(220, 70, 76, 25));
        inputMoph5_13->setValue(1);
        inputMoph5_14 = new QDoubleSpinBox(tab_2);
        inputMoph5_14->setObjectName(QStringLiteral("inputMoph5_14"));
        inputMoph5_14->setGeometry(QRect(290, 70, 76, 25));
        inputMoph5_14->setValue(1);
        inputMoph5_15 = new QDoubleSpinBox(tab_2);
        inputMoph5_15->setObjectName(QStringLiteral("inputMoph5_15"));
        inputMoph5_15->setGeometry(QRect(10, 100, 76, 25));
        inputMoph5_15->setValue(1);
        inputMoph5_16 = new QDoubleSpinBox(tab_2);
        inputMoph5_16->setObjectName(QStringLiteral("inputMoph5_16"));
        inputMoph5_16->setGeometry(QRect(80, 100, 76, 25));
        inputMoph5_16->setValue(1);
        inputMoph5_17 = new QDoubleSpinBox(tab_2);
        inputMoph5_17->setObjectName(QStringLiteral("inputMoph5_17"));
        inputMoph5_17->setGeometry(QRect(150, 100, 76, 25));
        inputMoph5_17->setValue(1);
        inputMoph5_18 = new QDoubleSpinBox(tab_2);
        inputMoph5_18->setObjectName(QStringLiteral("inputMoph5_18"));
        inputMoph5_18->setGeometry(QRect(220, 100, 76, 25));
        inputMoph5_18->setValue(1);
        inputMoph5_19 = new QDoubleSpinBox(tab_2);
        inputMoph5_19->setObjectName(QStringLiteral("inputMoph5_19"));
        inputMoph5_19->setGeometry(QRect(290, 100, 76, 25));
        inputMoph5_19->setValue(1);
        inputMoph5_20 = new QDoubleSpinBox(tab_2);
        inputMoph5_20->setObjectName(QStringLiteral("inputMoph5_20"));
        inputMoph5_20->setGeometry(QRect(10, 130, 76, 25));
        inputMoph5_20->setValue(1);
        inputMoph5_21 = new QDoubleSpinBox(tab_2);
        inputMoph5_21->setObjectName(QStringLiteral("inputMoph5_21"));
        inputMoph5_21->setGeometry(QRect(80, 130, 76, 25));
        inputMoph5_21->setValue(1);
        inputMoph5_22 = new QDoubleSpinBox(tab_2);
        inputMoph5_22->setObjectName(QStringLiteral("inputMoph5_22"));
        inputMoph5_22->setGeometry(QRect(150, 130, 76, 25));
        inputMoph5_22->setValue(1);
        inputMoph5_23 = new QDoubleSpinBox(tab_2);
        inputMoph5_23->setObjectName(QStringLiteral("inputMoph5_23"));
        inputMoph5_23->setGeometry(QRect(220, 130, 76, 25));
        inputMoph5_23->setValue(1);
        inputMoph5_24 = new QDoubleSpinBox(tab_2);
        inputMoph5_24->setObjectName(QStringLiteral("inputMoph5_24"));
        inputMoph5_24->setGeometry(QRect(290, 130, 76, 25));
        inputMoph5_24->setValue(1);
        tabWidget_2->addTab(tab_2, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        textEdit = new QTextEdit(tab_3);
        textEdit->setObjectName(QStringLiteral("textEdit"));
        textEdit->setGeometry(QRect(30, 26, 331, 141));
        tabWidget_2->addTab(tab_3, QString());
        dilationBtn = new QPushButton(MophologyWidget);
        dilationBtn->setObjectName(QStringLiteral("dilationBtn"));
        dilationBtn->setGeometry(QRect(10, 270, 91, 34));
        erosionBtn = new QPushButton(MophologyWidget);
        erosionBtn->setObjectName(QStringLiteral("erosionBtn"));
        erosionBtn->setGeometry(QRect(120, 270, 91, 34));
        openBtn = new QPushButton(MophologyWidget);
        openBtn->setObjectName(QStringLiteral("openBtn"));
        openBtn->setGeometry(QRect(230, 270, 91, 34));
        closeBtn = new QPushButton(MophologyWidget);
        closeBtn->setObjectName(QStringLiteral("closeBtn"));
        closeBtn->setGeometry(QRect(340, 270, 91, 34));
        thinningBtn = new QPushButton(MophologyWidget);
        thinningBtn->setObjectName(QStringLiteral("thinningBtn"));
        thinningBtn->setGeometry(QRect(120, 320, 101, 34));
        thickeningBtn = new QPushButton(MophologyWidget);
        thickeningBtn->setObjectName(QStringLiteral("thickeningBtn"));
        thickeningBtn->setGeometry(QRect(225, 320, 101, 34));
        line_8 = new QFrame(MophologyWidget);
        line_8->setObjectName(QStringLiteral("line_8"));
        line_8->setGeometry(QRect(10, 305, 421, 16));
        line_8->setFrameShape(QFrame::HLine);
        line_8->setFrameShadow(QFrame::Sunken);
        label_51 = new QLabel(MophologyWidget);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(10, 330, 121, 18));
        distanceBtn = new QPushButton(MophologyWidget);
        distanceBtn->setObjectName(QStringLiteral("distanceBtn"));
        distanceBtn->setGeometry(QRect(330, 320, 101, 34));
        skeletonBtn = new QPushButton(MophologyWidget);
        skeletonBtn->setObjectName(QStringLiteral("skeletonBtn"));
        skeletonBtn->setGeometry(QRect(130, 360, 81, 34));
        SkeletonReconBtn = new QPushButton(MophologyWidget);
        SkeletonReconBtn->setObjectName(QStringLiteral("SkeletonReconBtn"));
        SkeletonReconBtn->setGeometry(QRect(220, 360, 211, 34));
        line_9 = new QFrame(MophologyWidget);
        line_9->setObjectName(QStringLiteral("line_9"));
        line_9->setGeometry(QRect(10, 395, 421, 16));
        line_9->setFrameShape(QFrame::HLine);
        line_9->setFrameShadow(QFrame::Sunken);
        label_52 = new QLabel(MophologyWidget);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(10, 410, 91, 18));
        reconstructionBtn = new QPushButton(MophologyWidget);
        reconstructionBtn->setObjectName(QStringLiteral("reconstructionBtn"));
        reconstructionBtn->setGeometry(QRect(100, 410, 171, 34));
        label_53 = new QLabel(MophologyWidget);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(10, 230, 81, 18));
        inputAnchorRow = new QSpinBox(MophologyWidget);
        inputAnchorRow->setObjectName(QStringLiteral("inputAnchorRow"));
        inputAnchorRow->setGeometry(QRect(170, 230, 49, 25));
        inputAnchorRow->setValue(1);
        inputAnchorCol = new QSpinBox(MophologyWidget);
        inputAnchorCol->setObjectName(QStringLiteral("inputAnchorCol"));
        inputAnchorCol->setGeometry(QRect(310, 230, 49, 25));
        inputAnchorCol->setValue(1);
        label_54 = new QLabel(MophologyWidget);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(120, 230, 41, 18));
        label_55 = new QLabel(MophologyWidget);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(260, 230, 51, 18));
        watershedBtn = new QPushButton(MophologyWidget);
        watershedBtn->setObjectName(QStringLiteral("watershedBtn"));
        watershedBtn->setGeometry(QRect(280, 410, 151, 34));
        label_56 = new QLabel(centralWidget);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(10, 850, 101, 18));
        helpLabel = new QLabel(centralWidget);
        helpLabel->setObjectName(QStringLiteral("helpLabel"));
        helpLabel->setGeometry(QRect(10, 870, 81, 18));
        miniPSClass->setCentralWidget(centralWidget);
        statusBar = new QStatusBar(miniPSClass);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        miniPSClass->setStatusBar(statusBar);
        mainToolBar = new QToolBar(miniPSClass);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        miniPSClass->addToolBar(Qt::TopToolBarArea, mainToolBar);
        menuBar = new QMenuBar(miniPSClass);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1920, 30));
        menuFile = new QMenu(menuBar);
        menuFile->setObjectName(QStringLiteral("menuFile"));
        menuEdit = new QMenu(menuBar);
        menuEdit->setObjectName(QStringLiteral("menuEdit"));
        menucolor_operation = new QMenu(menuEdit);
        menucolor_operation->setObjectName(QStringLiteral("menucolor_operation"));
        menuchannel_split = new QMenu(menucolor_operation);
        menuchannel_split->setObjectName(QStringLiteral("menuchannel_split"));
        menubinary_analysis = new QMenu(menuEdit);
        menubinary_analysis->setObjectName(QStringLiteral("menubinary_analysis"));
        menudraw_histogram = new QMenu(menuEdit);
        menudraw_histogram->setObjectName(QStringLiteral("menudraw_histogram"));
        menugrayscale_adjustment = new QMenu(menuEdit);
        menugrayscale_adjustment->setObjectName(QStringLiteral("menugrayscale_adjustment"));
        menufilter = new QMenu(menuEdit);
        menufilter->setObjectName(QStringLiteral("menufilter"));
        menuedge_detection = new QMenu(menuEdit);
        menuedge_detection->setObjectName(QStringLiteral("menuedge_detection"));
        menusobel = new QMenu(menuedge_detection);
        menusobel->setObjectName(QStringLiteral("menusobel"));
        menuhough = new QMenu(menuEdit);
        menuhough->setObjectName(QStringLiteral("menuhough"));
        menuSettings = new QMenu(menuBar);
        menuSettings->setObjectName(QStringLiteral("menuSettings"));
        menuWindow_mode = new QMenu(menuSettings);
        menuWindow_mode->setObjectName(QStringLiteral("menuWindow_mode"));
        miniPSClass->setMenuBar(menuBar);

        menuBar->addAction(menuFile->menuAction());
        menuBar->addAction(menuEdit->menuAction());
        menuBar->addAction(menuSettings->menuAction());
        menuFile->addAction(actionopen_image);
        menuFile->addSeparator();
        menuFile->addAction(actionsave_image);
        menuFile->addSeparator();
        menuFile->addAction(actionminimize);
        menuFile->addAction(actionexit);
        menuEdit->addAction(actionundo);
        menuEdit->addAction(actionclean_all_layers);
        menuEdit->addAction(menucolor_operation->menuAction());
        menuEdit->addAction(menubinary_analysis->menuAction());
        menuEdit->addAction(actionresize);
        menuEdit->addAction(menudraw_histogram->menuAction());
        menuEdit->addAction(menufilter->menuAction());
        menuEdit->addAction(actionrotate);
        menuEdit->addAction(menugrayscale_adjustment->menuAction());
        menuEdit->addAction(menuedge_detection->menuAction());
        menuEdit->addAction(menuhough->menuAction());
        menuEdit->addAction(actionmophology);
        menucolor_operation->addAction(menuchannel_split->menuAction());
        menucolor_operation->addAction(actionRGB2GrayScale);
        menucolor_operation->addAction(actionHSB);
        menuchannel_split->addAction(actionRed);
        menuchannel_split->addAction(actionGreen);
        menuchannel_split->addAction(actionBlue);
        menubinary_analysis->addAction(actionOtus_Algo);
        menubinary_analysis->addAction(actiondouble_threshod);
        menudraw_histogram->addAction(actionR_hist);
        menudraw_histogram->addAction(actionG_hist);
        menudraw_histogram->addAction(actionB_hist);
        menudraw_histogram->addAction(actionEqualization);
        menugrayscale_adjustment->addAction(actionlinear);
        menugrayscale_adjustment->addAction(actionexp_log);
        menufilter->addAction(actionfilter_2);
        menufilter->addAction(action3_3_self_define);
        menuedge_detection->addAction(menusobel->menuAction());
        menuedge_detection->addAction(actionlaplace);
        menuedge_detection->addAction(actioncanny);
        menusobel->addAction(actionsobelX);
        menusobel->addAction(actionsobelY);
        menusobel->addAction(actionsobelXY);
        menuhough->addAction(actionhoughLine);
        menuhough->addAction(actionhoughCircle);
        menuSettings->addSeparator();
        menuSettings->addAction(menuWindow_mode->menuAction());
        menuWindow_mode->addAction(actionfull_screen);
        menuWindow_mode->addAction(actionwindowed);

        retranslateUi(miniPSClass);
        QObject::connect(exitBtn, SIGNAL(clicked()), miniPSClass, SLOT(close()));
        QObject::connect(tabWidget, SIGNAL(tabBarClicked(int)), miniPSClass, SLOT(update()));

        exitBtn->setDefault(true);
        tabWidget->setCurrentIndex(0);
        tabWidget_2->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(miniPSClass);
    } // setupUi

    void retranslateUi(QMainWindow *miniPSClass)
    {
        miniPSClass->setWindowTitle(QApplication::translate("miniPSClass", "miniPS", Q_NULLPTR));
        actionopen_image->setText(QApplication::translate("miniPSClass", "load image", Q_NULLPTR));
#ifndef QT_NO_STATUSTIP
        actionopen_image->setStatusTip(QString());
#endif // QT_NO_STATUSTIP
        actionsave_image->setText(QApplication::translate("miniPSClass", "save", Q_NULLPTR));
#ifndef QT_NO_WHATSTHIS
        actionsave_image->setWhatsThis(QApplication::translate("miniPSClass", "to save image", Q_NULLPTR));
#endif // QT_NO_WHATSTHIS
        actionminimize->setText(QApplication::translate("miniPSClass", "minimize", Q_NULLPTR));
        actionundo->setText(QApplication::translate("miniPSClass", "undo", Q_NULLPTR));
        actionfull_screen->setText(QApplication::translate("miniPSClass", "full screen", Q_NULLPTR));
        actionwindowed->setText(QApplication::translate("miniPSClass", "windowed", Q_NULLPTR));
        actionexit->setText(QApplication::translate("miniPSClass", "exit", Q_NULLPTR));
        actionclean_all_layers->setText(QApplication::translate("miniPSClass", "clean all layers", Q_NULLPTR));
        actionRGB2GrayScale->setText(QApplication::translate("miniPSClass", "RGB2GrayScale", Q_NULLPTR));
        actionRed->setText(QApplication::translate("miniPSClass", "Red", Q_NULLPTR));
        actionGreen->setText(QApplication::translate("miniPSClass", "Green", Q_NULLPTR));
        actionBlue->setText(QApplication::translate("miniPSClass", "Blue", Q_NULLPTR));
        actionHSB->setText(QApplication::translate("miniPSClass", "HSB", Q_NULLPTR));
        actionOtus_Algo->setText(QApplication::translate("miniPSClass", "Otus Algo", Q_NULLPTR));
        actiondouble_threshod->setText(QApplication::translate("miniPSClass", "double threshod", Q_NULLPTR));
        actionresize->setText(QApplication::translate("miniPSClass", "resize", Q_NULLPTR));
        actionR_hist->setText(QApplication::translate("miniPSClass", "R hist", Q_NULLPTR));
        actionG_hist->setText(QApplication::translate("miniPSClass", "G hist", Q_NULLPTR));
        actionB_hist->setText(QApplication::translate("miniPSClass", "B hist", Q_NULLPTR));
        actionEqualization->setText(QApplication::translate("miniPSClass", "Equalization", Q_NULLPTR));
        actionrotate->setText(QApplication::translate("miniPSClass", "rotate", Q_NULLPTR));
        actionlinear->setText(QApplication::translate("miniPSClass", "linear", Q_NULLPTR));
        actionexp_log->setText(QApplication::translate("miniPSClass", "exp/log", Q_NULLPTR));
        actionlogarithm->setText(QApplication::translate("miniPSClass", "logarithm", Q_NULLPTR));
        actionfilter_2->setText(QApplication::translate("miniPSClass", "default", Q_NULLPTR));
        action3_3_self_define->setText(QApplication::translate("miniPSClass", "3*3 self-define", Q_NULLPTR));
        actionlaplace->setText(QApplication::translate("miniPSClass", "laplace", Q_NULLPTR));
        actioncanny->setText(QApplication::translate("miniPSClass", "canny", Q_NULLPTR));
        actionsobelX->setText(QApplication::translate("miniPSClass", "sobelX", Q_NULLPTR));
        actionsobelY->setText(QApplication::translate("miniPSClass", "sobelY", Q_NULLPTR));
        actionsobelXY->setText(QApplication::translate("miniPSClass", "sobelXY", Q_NULLPTR));
        actiongrayscale_mophology->setText(QApplication::translate("miniPSClass", "grayscale mophology", Q_NULLPTR));
        actionhoughLine->setText(QApplication::translate("miniPSClass", "houghLine", Q_NULLPTR));
        actionhoughCircle->setText(QApplication::translate("miniPSClass", "houghCircle", Q_NULLPTR));
        actiondilation->setText(QApplication::translate("miniPSClass", "dilation", Q_NULLPTR));
        actionerosion->setText(QApplication::translate("miniPSClass", "erosion", Q_NULLPTR));
        actionopen->setText(QApplication::translate("miniPSClass", "open", Q_NULLPTR));
        actionclose->setText(QApplication::translate("miniPSClass", "close", Q_NULLPTR));
        actionthinning_binary->setText(QApplication::translate("miniPSClass", "thinning(binary only)", Q_NULLPTR));
        actionthickening_binary_only->setText(QApplication::translate("miniPSClass", "thickening(binary only)", Q_NULLPTR));
        actiondistance_transform_binary_only->setText(QApplication::translate("miniPSClass", "distance transform(binary only)", Q_NULLPTR));
        actionskeleton_binary_only->setText(QApplication::translate("miniPSClass", "skeleton(binary only)", Q_NULLPTR));
        actionskeleton_reconstruction_binary_only->setText(QApplication::translate("miniPSClass", "skeleton reconstruction(binary only)", Q_NULLPTR));
        actionwatershed->setText(QApplication::translate("miniPSClass", "watershed", Q_NULLPTR));
        actionbinary->setText(QApplication::translate("miniPSClass", "binary", Q_NULLPTR));
        actiongrayscale->setText(QApplication::translate("miniPSClass", "grayscale", Q_NULLPTR));
        actionmophology->setText(QApplication::translate("miniPSClass", "mophology", Q_NULLPTR));
        actionDocument->setText(QApplication::translate("miniPSClass", "Document", Q_NULLPTR));
        exitBtn->setText(QApplication::translate("miniPSClass", "QUIT", Q_NULLPTR));
        groupBox->setTitle(QApplication::translate("miniPSClass", "Inpector", Q_NULLPTR));
        zoomOutBtn->setText(QApplication::translate("miniPSClass", "-", Q_NULLPTR));
        zoomInBtn->setText(QApplication::translate("miniPSClass", "+", Q_NULLPTR));
        label_scaleVal->setText(QApplication::translate("miniPSClass", "100%", Q_NULLPTR));
        label->setText(QApplication::translate("miniPSClass", "X:", Q_NULLPTR));
        label_2->setText(QApplication::translate("miniPSClass", "Y:", Q_NULLPTR));
        label_3->setText(QApplication::translate("miniPSClass", "W:", Q_NULLPTR));
        label_4->setText(QApplication::translate("miniPSClass", "H:", Q_NULLPTR));
        label_posX->setText(QApplication::translate("miniPSClass", "0", Q_NULLPTR));
        label_posY->setText(QApplication::translate("miniPSClass", "0", Q_NULLPTR));
        label_width->setText(QApplication::translate("miniPSClass", "0", Q_NULLPTR));
        label_height->setText(QApplication::translate("miniPSClass", "0", Q_NULLPTR));
        label_5->setText(QApplication::translate("miniPSClass", "R:", Q_NULLPTR));
        label_6->setText(QApplication::translate("miniPSClass", "G:", Q_NULLPTR));
        label_7->setText(QApplication::translate("miniPSClass", "B:", Q_NULLPTR));
        label_rVal->setText(QApplication::translate("miniPSClass", "0", Q_NULLPTR));
        label_gVal->setText(QApplication::translate("miniPSClass", "0", Q_NULLPTR));
        label_bVal->setText(QApplication::translate("miniPSClass", "0", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(layer1), QApplication::translate("miniPSClass", "Image1", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(layer2), QApplication::translate("miniPSClass", "Image2", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(layer3), QApplication::translate("miniPSClass", "Image3", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(layer4), QApplication::translate("miniPSClass", "Image4", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(layer5), QApplication::translate("miniPSClass", "Image5", Q_NULLPTR));
        label_imagesize->setText(QApplication::translate("miniPSClass", "0 * 0 px", Q_NULLPTR));
        normalModeBtn->setText(QString());
        slctModeBtn->setText(QString());
        pushButton->setText(QString());
        pushButton_2->setText(QString());
        picked_color1->setText(QString());
        picked_color2->setText(QString());
#ifndef QT_NO_WHATSTHIS
        colorSwitchBtn->setWhatsThis(QApplication::translate("miniPSClass", "Exchange two gethered color", Q_NULLPTR));
#endif // QT_NO_WHATSTHIS
        colorSwitchBtn->setText(QString());
#ifndef QT_NO_WHATSTHIS
        colorResetBtn->setWhatsThis(QApplication::translate("miniPSClass", "Reset the gethered color to black and white", Q_NULLPTR));
#endif // QT_NO_WHATSTHIS
        colorResetBtn->setText(QString());
        getColorBtn->setText(QString());
        cutBtn->setText(QString());
        addBtn->setText(QString());
        subtractionBtn->setText(QString());
        multiplicationBtn->setText(QString());
        spinBtn->setText(QString());
        helloWorldBtn->setText(QApplication::translate("miniPSClass", "HelloWorld", Q_NULLPTR));
        label_9->setText(QApplication::translate("miniPSClass", "H\357\274\232", Q_NULLPTR));
        label_10->setText(QApplication::translate("miniPSClass", "S\357\274\232", Q_NULLPTR));
        label_11->setText(QApplication::translate("miniPSClass", "V:", Q_NULLPTR));
        HSVokBtn->setText(QApplication::translate("miniPSClass", "OK", Q_NULLPTR));
        label_12->setText(QApplication::translate("miniPSClass", "Threshod 1:", Q_NULLPTR));
        label_13->setText(QApplication::translate("miniPSClass", "Threshod 2:", Q_NULLPTR));
        doubleThreshodOkBtn->setText(QApplication::translate("miniPSClass", "OK", Q_NULLPTR));
        label_8->setText(QApplication::translate("miniPSClass", "image1 + image2:", Q_NULLPTR));
        label_14->setText(QApplication::translate("miniPSClass", "image1:", Q_NULLPTR));
        label_15->setText(QApplication::translate("miniPSClass", "image2:", Q_NULLPTR));
        label_16->setText(QApplication::translate("miniPSClass", "weight:", Q_NULLPTR));
        label_17->setText(QApplication::translate("miniPSClass", "weight:", Q_NULLPTR));
        addOkBtn->setText(QApplication::translate("miniPSClass", "OK", Q_NULLPTR));
        label_18->setText(QApplication::translate("miniPSClass", "xPos:", Q_NULLPTR));
        label_19->setText(QApplication::translate("miniPSClass", "yPos:", Q_NULLPTR));
        label_20->setText(QApplication::translate("miniPSClass", "image1 - image2:", Q_NULLPTR));
        label_21->setText(QApplication::translate("miniPSClass", "image1:", Q_NULLPTR));
        label_22->setText(QApplication::translate("miniPSClass", "image2:", Q_NULLPTR));
        label_23->setText(QApplication::translate("miniPSClass", "xPos:", Q_NULLPTR));
        label_24->setText(QApplication::translate("miniPSClass", "yPos:", Q_NULLPTR));
        substractionOkBtn->setText(QApplication::translate("miniPSClass", "OK", Q_NULLPTR));
        label_25->setText(QApplication::translate("miniPSClass", "image1 * image2:", Q_NULLPTR));
        label_26->setText(QApplication::translate("miniPSClass", "image1:", Q_NULLPTR));
        label_27->setText(QApplication::translate("miniPSClass", "image2:", Q_NULLPTR));
        multiplicationOkBtn->setText(QApplication::translate("miniPSClass", "OK", Q_NULLPTR));
        label_28->setText(QApplication::translate("miniPSClass", "image1 / image2:", Q_NULLPTR));
        label_29->setText(QApplication::translate("miniPSClass", "image1:", Q_NULLPTR));
        label_30->setText(QApplication::translate("miniPSClass", "image2:", Q_NULLPTR));
        divisionOkBtn->setText(QApplication::translate("miniPSClass", "OK", Q_NULLPTR));
        label_31->setText(QApplication::translate("miniPSClass", "Resize:", Q_NULLPTR));
        inputChoiceLINEAR->setText(QApplication::translate("miniPSClass", "LINEAR", Q_NULLPTR));
        inputChoiceNN->setText(QApplication::translate("miniPSClass", "NN", Q_NULLPTR));
        label_32->setText(QApplication::translate("miniPSClass", "width:", Q_NULLPTR));
        label_33->setText(QApplication::translate("miniPSClass", "height:", Q_NULLPTR));
        resizeOkBtn->setText(QApplication::translate("miniPSClass", "OK", Q_NULLPTR));
        label_34->setText(QApplication::translate("miniPSClass", "Filter:", Q_NULLPTR));
        inputFilterChoiceBox->setText(QApplication::translate("miniPSClass", "Box", Q_NULLPTR));
        inputFilterChoiceMedian->setText(QApplication::translate("miniPSClass", "Median", Q_NULLPTR));
        inputFilterChoiceGaussian->setText(QApplication::translate("miniPSClass", "Gaussian", Q_NULLPTR));
        label_35->setText(QApplication::translate("miniPSClass", "Kernel Size:", Q_NULLPTR));
        filterOkBtn->setText(QApplication::translate("miniPSClass", "OK", Q_NULLPTR));
        label_36->setText(QApplication::translate("miniPSClass", "Rotate:", Q_NULLPTR));
        label_37->setText(QApplication::translate("miniPSClass", "Theta:", Q_NULLPTR));
        rotateOkBtn->setText(QApplication::translate("miniPSClass", "OK", Q_NULLPTR));
        inputRotateChoiceNN->setText(QApplication::translate("miniPSClass", "NN", Q_NULLPTR));
        inputRotateChoiceLINEAR->setText(QApplication::translate("miniPSClass", "LINEAR", Q_NULLPTR));
        label_38->setText(QApplication::translate("miniPSClass", "rad", Q_NULLPTR));
        label_39->setText(QApplication::translate("miniPSClass", "Grayscale adjustment:  linear", Q_NULLPTR));
        label_40->setText(QApplication::translate("miniPSClass", "Display Label", Q_NULLPTR));
        GSALinearOkBtn->setText(QApplication::translate("miniPSClass", "OK", Q_NULLPTR));
        label_41->setText(QApplication::translate("miniPSClass", "D", Q_NULLPTR));
        label_42->setText(QApplication::translate("miniPSClass", "C", Q_NULLPTR));
        label_43->setText(QApplication::translate("miniPSClass", "A", Q_NULLPTR));
        label_44->setText(QApplication::translate("miniPSClass", "B", Q_NULLPTR));
        inputLinearGSAChoiceRGB->setText(QApplication::translate("miniPSClass", "RGB", Q_NULLPTR));
        inputLinearGSAChoiceR->setText(QApplication::translate("miniPSClass", "R", Q_NULLPTR));
        inputLinearGSAChoiceG->setText(QApplication::translate("miniPSClass", "G", Q_NULLPTR));
        inputLinearGSAChoiceB->setText(QApplication::translate("miniPSClass", "B", Q_NULLPTR));
        label_45->setText(QApplication::translate("miniPSClass", "Grayscale adjustment: exp/log", Q_NULLPTR));
        label_46->setText(QApplication::translate("miniPSClass", "A:", Q_NULLPTR));
        label_47->setText(QApplication::translate("miniPSClass", "B:", Q_NULLPTR));
        label_48->setText(QApplication::translate("miniPSClass", "C:", Q_NULLPTR));
        inputUGSAexp->setText(QApplication::translate("miniPSClass", "exp", Q_NULLPTR));
        inputUGSAlog->setText(QApplication::translate("miniPSClass", "log", Q_NULLPTR));
        UGSAOkBtn->setText(QApplication::translate("miniPSClass", "OK", Q_NULLPTR));
        label_49->setText(QApplication::translate("miniPSClass", "Self-define Filter:", Q_NULLPTR));
        selfFilterOkBtn->setText(QApplication::translate("miniPSClass", "OK", Q_NULLPTR));
        label_50->setText(QApplication::translate("miniPSClass", "Mophology:", Q_NULLPTR));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab), QApplication::translate("miniPSClass", "3*3", Q_NULLPTR));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_2), QApplication::translate("miniPSClass", "5*5", Q_NULLPTR));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_3), QApplication::translate("miniPSClass", "m*n", Q_NULLPTR));
        dilationBtn->setText(QApplication::translate("miniPSClass", "dilation", Q_NULLPTR));
        erosionBtn->setText(QApplication::translate("miniPSClass", "erosion", Q_NULLPTR));
        openBtn->setText(QApplication::translate("miniPSClass", "open", Q_NULLPTR));
        closeBtn->setText(QApplication::translate("miniPSClass", "close", Q_NULLPTR));
        thinningBtn->setText(QApplication::translate("miniPSClass", "thinning", Q_NULLPTR));
        thickeningBtn->setText(QApplication::translate("miniPSClass", "thickening", Q_NULLPTR));
        label_51->setText(QApplication::translate("miniPSClass", "Binary Only:", Q_NULLPTR));
        distanceBtn->setText(QApplication::translate("miniPSClass", "distance", Q_NULLPTR));
        skeletonBtn->setText(QApplication::translate("miniPSClass", "skeleton", Q_NULLPTR));
        SkeletonReconBtn->setText(QApplication::translate("miniPSClass", "skeletonReconstruction", Q_NULLPTR));
        label_52->setText(QApplication::translate("miniPSClass", "Grayscale:", Q_NULLPTR));
        reconstructionBtn->setText(QApplication::translate("miniPSClass", "reconstruction", Q_NULLPTR));
        label_53->setText(QApplication::translate("miniPSClass", "anchor:", Q_NULLPTR));
        label_54->setText(QApplication::translate("miniPSClass", "row:", Q_NULLPTR));
        label_55->setText(QApplication::translate("miniPSClass", "col:", Q_NULLPTR));
        watershedBtn->setText(QApplication::translate("miniPSClass", "watershed", Q_NULLPTR));
        label_56->setText(QApplication::translate("miniPSClass", "miniPS:V1.0", Q_NULLPTR));
        helpLabel->setText(QApplication::translate("miniPSClass", "adsfasdf", Q_NULLPTR));
        menuFile->setTitle(QApplication::translate("miniPSClass", "File", Q_NULLPTR));
        menuEdit->setTitle(QApplication::translate("miniPSClass", "Edit", Q_NULLPTR));
        menucolor_operation->setTitle(QApplication::translate("miniPSClass", "color operation", Q_NULLPTR));
        menuchannel_split->setTitle(QApplication::translate("miniPSClass", "channel split", Q_NULLPTR));
        menubinary_analysis->setTitle(QApplication::translate("miniPSClass", "binary analysis", Q_NULLPTR));
        menudraw_histogram->setTitle(QApplication::translate("miniPSClass", "histogram", Q_NULLPTR));
        menugrayscale_adjustment->setTitle(QApplication::translate("miniPSClass", "grayscale adjustment", Q_NULLPTR));
        menufilter->setTitle(QApplication::translate("miniPSClass", "filter", Q_NULLPTR));
        menuedge_detection->setTitle(QApplication::translate("miniPSClass", "edge detection", Q_NULLPTR));
        menusobel->setTitle(QApplication::translate("miniPSClass", "sobel", Q_NULLPTR));
        menuhough->setTitle(QApplication::translate("miniPSClass", "hough", Q_NULLPTR));
        menuSettings->setTitle(QApplication::translate("miniPSClass", "Settings", Q_NULLPTR));
        menuWindow_mode->setTitle(QApplication::translate("miniPSClass", "window mode", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class miniPSClass: public Ui_miniPSClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MINIPS_H
